name: CI Build

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ci:
    uses: daniel-kraemer/.github/.github/workflows/ci.yml@main
    secrets: inherit
