name: CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  ci:
    uses: daniel-kraemer/.github/.github/workflows/ci.yml@main
    secrets: inherit
