on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  owasp:
    uses:  daniel-kraemer/.github/.github/workflows/owasp.yml@main
    secrets: inherit
