on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  pull-requests: read
jobs:
  sonarqube:
    uses:  daniel-kraemer/.github/.github/workflows/sonarqube.yml@main
    secrets: inherit
